#
# Mica server main configuration file.
# See documentation at: http://wiki.obiba.org/display/MICADOC/Mica+Configuration+Files
#

# HTTP server configuration
server:
    port: 8082
    address: localhost

https:
    port: 8445

# Opal: data dictionaries, summaries and taxonomies
opal:
  url: https://localhost:8443
  username: administrator
  password: password

# Agate: user realm and application services configuration
agate:
  url: https://localhost:8444
  application:
    name: mica
    key: changeit

# Elasticsearch: search engine configuration
elasticsearch:
  dataNode: true
  clusterName: mica
  shards: 5
  replicas: 1
  settings: "http.enabled: false"
  maxConcurrentJoinQueries: 4
  concurrentJoinQueriesWaitTimeout: 30000

# Shiro: user directory configuration
shiro:
  password:
    nbHashIterations: 10000
    salt: mica

#
# Other advanced settings
#

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mica
  profiles: prod
  thymeleaf:
    mode: XHTML
    cache: true
  mail:
    host: localhost
    port: 25
    user:
    password:
    protocol: smtp
    tls: false
    auth: false
  messageSource:
    cacheSeconds: 1

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false
endpoints.enabled: false

async:
    poolSize: 30
    queueCapacity: 100000
    opal:
      poolSize: 30
      queueCapacity: 100000
