# default advanced settings
spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
    messageSource:
        cacheSeconds: 1
    freemarker:
      template-loader-path: classpath:/web/,classpath:/static/templates/,classpath:/public/templates/,classpath:/templates/
      request-context-attribute: rc

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

async:
    poolSize: 1
    queueCapacity: 100000
    opal:
        poolSize: 30
        queueCapacity: 100000

portal.draftResource.urlPattern: "{portalUrl}/mica/{resourceType}/{resourceId}/draft/{shareKey}"

#
# Plugins
#

plugins:
  updateSite: https://plugins.obiba.org

#
# Security
#

login:
  maxTry: 3
  trialTime: 300
  banTime: 300
